import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  docs: [
    "introduction",
    "credentials",
    {
      type: "category",
      label: "Arquitetura",
      items: [
        "architecture/arch-patterns",
        "architecture/controllers",
        "architecture/services",
        "architecture/repositories",
      ],
    },
    {
      type: "category",
      label: "Proposição",
      items: ["proposition/create-proposition"],
    },
    {
      type: "category",
      label: "Emenda",
      items: ["amendment/create-amendment"],
    },
    {
      type: "category",
      label: "Veto",
      items: ["veto/create-veto"],
    },
    {
      type: "category",
      label: "Regime de Tramitação",
      items: ["procedure/create-procedure"],
    },
    {
      type: "category",
      label: "Anexo",
      items: ["attachment/create-attachment"],
    },
    {
      type: "category",
      label: "Movimentação Interna",
      items: ["internal-movement/create-internal-movement"],
    },
    {
      type: "category",
      label: "Protocolo",
      items: ["protocol/create-protocol"],
    },
    {
      type: "category",
      label: "Período de Pauta",
      items: ["docket-period/create-docket-period"],
    },
    {
      type: "category",
      label: "Comissão",
      items: ["committee/create-committee"],
    },
    {
      type: "category",
      label: "Relator na Comissão",
      items: ["committee-reporter/create-committee-reporter"],
    },
    {
      type: "category",
      label: "Votação na Comissão",
      items: ["committee-voting/create-committee-voting"],
    },
    {
      type: "category",
      label: "Votação no Plenário",
      items: ["plenary-voting/create-plenary-voting"],
    },
    {
      type: "category",
      label: "Ofício",
      items: ["official-letter/create-official-letter"],
    },
    {
      type: "category",
      label: "Texto Final",
      items: ["final-text/create-final-text"],
    },
    // {
    //   type: "category",
    //   label: "Quick Start",
    //   link: {
    //     type: "generated-index",
    //     description:
    //       "Let's learn about the most important Docusaurus concepts!",
    //     image: "/img/logo.png",
    //     keywords: ["start"],
    //   },
    //   collapsed: false,
    //   items: ["quick-start/overview-of-apps", "quick-start/getting-started"],
    // // },
    // {
    //   type: "category",
    //   label: "Topics",
    //   link: {
    //     type: "generated-index",
    //     image: "/img/logo.png",
    //     keywords: ["topics"],
    //   },
    //   collapsed: false,
    //   items: ["topics/rate-limits"],
    // },
    // {
    //   items: [
    //     "guides/creating-pages",
    //     {
    //       type: "category",
    //       label: "Docs",
    //       link: {
    //         type: "doc",
    //         id: "guides/docs/introduction",
    //       },
    //       items: [
    //         "guides/docs/create-doc",
    //         {
    //           type: "category",
    //           label: "Sidebar",
    //           link: {
    //             type: "doc",
    //             id: "guides/docs/sidebar/index",
    //           },
    //           items: [
    //             "guides/docs/sidebar/items",
    //             "guides/docs/sidebar/autogenerated",
    //             "guides/docs/sidebar/multiple-sidebars",
    //           ],
    //         },
    //         "guides/docs/versioning",
    //         "guides/docs/multi-instance",
    //       ],
    //     },
    //     "blog",
    //     {
    //       type: "category",
    //       label: "Markdown Features",
    //       link: {
    //         type: "doc",
    //         id: "guides/markdown-features/introduction",
    //       },
    //       items: [
    //         "guides/markdown-features/react",
    //         "guides/markdown-features/tabs",
    //         "guides/markdown-features/code-blocks",
    //         "guides/markdown-features/admonitions",
    //         "guides/markdown-features/toc",
    //         "guides/markdown-features/assets",
    //         "guides/markdown-features/links",
    //         "guides/markdown-features/plugins",
    //         "guides/markdown-features/math-equations",
    //         "guides/markdown-features/diagrams",
    //         "guides/markdown-features/head-metadata",
    //       ],
    //     },
    //     "styling-layout",
    //     "swizzling",
    //     "static-assets",
    //     "search",
    //     "browser-support",
    //     "seo",
    //     "using-plugins",
    //     "deployment",
    //     {
    //       type: "category",
    //       label: "Internationalization",
    //       link: { type: "doc", id: "i18n/introduction" },
    //       items: [
    //         {
    //           type: "doc",
    //           id: "i18n/tutorial",
    //           label: "Tutorial",
    //         },
    //         {
    //           type: "doc",
    //           id: "i18n/git",
    //           label: "Using Git",
    //         },
    //         {
    //           type: "doc",
    //           id: "i18n/crowdin",
    //           label: "Using Crowdin",
    //         },
    //       ],
    //     },
    //     "guides/whats-next",
    //   ],
    // },
    // {
    //   type: "category",
    //   label: "Advanced Guides",
    //   link: { type: "doc", id: "advanced/index" },
    //   items: [
    //     "advanced/architecture",
    //     "advanced/plugins",
    //     "advanced/routing",
    //     "advanced/ssg",
    //     "advanced/client",
    //   ],
    // },
    // {
    //   type: "category",
    //   label: "Upgrading",
    //   link: {
    //     type: "doc",
    //     id: "migration/index",
    //   },
    //   items: [
    //     "migration/v3",
    //     {
    //       type: "category",
    //       label: "To Docusaurus v2",
    //       items: [
    //         "migration/v2/migration-overview",
    //         "migration/v2/migration-automated",
    //         "migration/v2/migration-manual",
    //         "migration/v2/migration-versioned-sites",
    //         "migration/v2/migration-translated-sites",
    //       ],
    //     },
    //   ],
    // },
  ],
  // api: [
  //   "cli",
  //   "docusaurus-core",
  //   {
  //     type: "autogenerated",
  //     dirName: "api",
  //   },
  // ],
};
export default sidebars;
